-- Create emails table to store synced emails
create table "public"."emails" (
    "id" bigint generated by default as identity not null,
    "message_id" text, -- IMAP message ID or unique identifier
    "imap_uid" bigint, -- IMAP UID for tracking
    "from_email" text not null,
    "from_name" text,
    "to_emails" jsonb not null, -- Array of {email, name} objects
    "cc_emails" jsonb,
    "bcc_emails" jsonb,
    "subject" text,
    "body_text" text,
    "body_html" text,
    "date" timestamp with time zone not null,
    "processed" boolean not null default false, -- Whether note has been created
    "contact_id" bigint, -- Matched contact (if found)
    "sales_id" bigint, -- Sales user who owns this email
    "created_at" timestamp with time zone not null default now(),
    constraint "emails_pkey" PRIMARY KEY ("id")
);

-- Create index for fast lookups
create unique index "emails_message_id_idx" on public.emails (message_id) where message_id is not null;
create index "emails_imap_uid_idx" on public.emails (imap_uid);
create index "emails_from_email_idx" on public.emails (from_email);
create index "emails_processed_idx" on public.emails (processed);
create index "emails_contact_id_idx" on public.emails (contact_id);

-- Enable RLS
alter table "public"."emails" enable row level security;

-- RLS policy: users can only see their own emails
create policy "Users can view their own emails"
  on public.emails
  for select
  using (auth.uid() in (select user_id from public.sales where id = sales_id));

-- RLS policy: service role can do everything (for edge functions)
create policy "Service role can manage emails"
  on public.emails
  for all
  using (true)
  with check (true);

-- Foreign key to contacts
alter table "public"."emails" add constraint "emails_contact_id_fkey" 
  FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE SET NULL;

-- Foreign key to sales
alter table "public"."emails" add constraint "emails_sales_id_fkey" 
  FOREIGN KEY (sales_id) REFERENCES sales(id) ON UPDATE CASCADE ON DELETE CASCADE;

