-- Create table to store Zoho Mail OAuth tokens per user
create table "public"."zoho_oauth_tokens" (
    "id" bigint generated by default as identity not null,
    "sales_id" bigint not null,
    "access_token" text not null,
    "refresh_token" text not null,
    "expires_at" timestamp with time zone not null,
    "account_id" text,
    "account_email" text,
    "data_center" text default 'us',
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    constraint "zoho_oauth_tokens_pkey" PRIMARY KEY ("id")
);

-- Create unique index to ensure one token per sales user
create unique index "zoho_oauth_tokens_sales_id_idx" on public.zoho_oauth_tokens (sales_id);

-- Enable RLS
alter table "public"."zoho_oauth_tokens" enable row level security;

-- RLS policy: users can only see their own tokens
create policy "Users can view their own Zoho tokens"
  on public.zoho_oauth_tokens
  for select
  using (auth.uid() in (select user_id from public.sales where id = sales_id));

-- RLS policy: users can insert/update their own tokens
create policy "Users can manage their own Zoho tokens"
  on public.zoho_oauth_tokens
  for all
  using (auth.uid() in (select user_id from public.sales where id = sales_id))
  with check (auth.uid() in (select user_id from public.sales where id = sales_id));

-- RLS policy: service role can do everything (for edge functions)
create policy "Service role can manage Zoho tokens"
  on public.zoho_oauth_tokens
  for all
  using (true)
  with check (true);

-- Foreign key to sales
alter table "public"."zoho_oauth_tokens" add constraint "zoho_oauth_tokens_sales_id_fkey" 
  FOREIGN KEY (sales_id) REFERENCES sales(id) ON UPDATE CASCADE ON DELETE CASCADE;


